<div class="text-center">
    <h1 class="text-center bg-primary text-white mt-3 p-2"> Welcome to Janjetina </h1>

    <h6 class="mt-3"> Pick some of our products and never get hungry! </h6>

    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="product/availableProducts?id=1"> Pizza </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="product/availableProducts?id=2"> Barbecue </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="product/availableProducts?id=3"> Drink </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="product/availableProducts?id=4"> Salad </a>
        </li>
    </ul>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d987.5978989737171!2d18.6275733562765!3d45.563443656932925!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475ce72c2830a425%3A0x75ccb91c0592d0b!2sUl.%20Josipa%20Kozarca%2016%2C%2031220%2C%20Vi%C5%A1njevac!5e0!3m2!1shr!2shr!4v1681151858236!5m2!1shr!2shr" 
        width="1000" 
        height="500" 
        style="border:0;" 
        allowfullscreen="" 
        loading="lazy" 
        referrerpolicy="no-referrer-when-downgrade">
    </iframe>
</div>

