<!DOCTYPE html>
<footer class="text-center mt-3">
    <div>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d987.5978989737171!2d18.6275733562765!3d45.563443656932925!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475ce72c2830a425%3A0x75ccb91c0592d0b!2sUl.%20Josipa%20Kozarca%2016%2C%2031220%2C%20Vi%C5%A1njevac!5e0!3m2!1shr!2shr!4v1681151858236!5m2!1shr!2shr" 
        width="1000" 
        height="500" 
        style="border:0;" 
        allowfullscreen="" 
        loading="lazy" 
        referrerpolicy="no-referrer-when-downgrade">
    </iframe>
    </div>
    <hr>
    <p>
        <?php
            use Core\App;
            echo App::config('appTitle')
        ?>
        &copy;  Edunova 2023 <br>
        <a href="https://github.com/Filip-Janjesic" target="_blank" title="About Me">About Me</a>
    </p>
</footer>